demonstrator:
  num_iterations: 500
  num_initial_iterations: 100
  random_agent: False
  epsilon: 0.2
  decay: 1
  optimistic: False
  social_agent: False
learner:
  num_iterations: 500
  num_initial_iterations: 100
  random_agent: False
  epsilon: 0.2
  decay: 1
  optimistic: False
  social_agent: True
  observe_simultaneously: False
  observe_action_only: True
  observe_best_arm: False
  prob_observe: # Leave blank for None
  prob_arm_exclusion: # Probability to exclude the arms (ignored if observe_best_arm False)