demonstrator:
  num_iterations: 1000
  num_initial_iterations: 100
  random_agent: False
  social_agent: False
learner:
  num_iterations: 1000
  num_initial_iterations: 100
  random_agent: False
  social_agent: True
  observe_simultaneously: True
  observe_action_only: True
  observe_current_iteration: True
  prob_observe: # Leave blank for None
  prob_sample_nonsocial_arms: 
  prob_arm_exclusion: 0.5 # 