demonstrator:
  num_iterations: 1000
  social_agent: False
learner:
  num_iterations: 1000
  social_agent: True
  observe_simultaneously: False
  observe_action_only: True
  observe_best_arm: True
  prob_observe: # Leave blank for None
  prob_arm_exclusion: # Currently doesnt matter